# Generated by Django 5.2.13 on 2026-04-29 12:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('course_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only alphabets and spaces are allowed.', regex='^[A-Za-z ]+$')])),
                ('Last_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only alphabets and spaces are allowed.', regex='^[A-Za-z ]+$')])),
                ('dob', models.DateField()),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=3)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Enter a proper email (example: name@gmail.com)', regex='^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$')])),
                ('address', models.TextField()),
                ('guardian_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only alphabets and spaces are allowed.', regex='^[A-Za-z ]+$')])),
                ('guardian_phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enquiry', 'Enquiry'), ('confirmed', 'Confirmed'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped')], default='enquiry', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='admissions.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(choices=[('Batch A', 'Batch A'), ('Batch B', 'Batch B'), ('Batch C', 'Batch C')], max_length=10)),
                ('start_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Partial', 'Partial')], max_length=20)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='admissions.admission')),
            ],
        ),
    ]
