# Generated by Django 5.2.13 on 2026-06-02 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='course',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='course_name',
        ),
    ]
