# Generated by Django 5.2.13 on 2026-06-02 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('topic_covered', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('next_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('trainer_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_logs', to='student_attendance_management.batch')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabus_logs', to='student_attendance_management.trainer')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
